services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: covibe-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DATABASE_URL=sqlite:///app/data/covibe.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - covibe-network

  # Frontend service - commented out due to build issues
  # Uncomment and fix build issues if you need the full web interface
  # For development, run: cd web && npm run dev
  # frontend:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   container_name: covibe-frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   restart: unless-stopped
  #   networks:
  #     - covibe-network

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: covibe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - covibe-network

networks:
  covibe-network:
    driver: bridge

volumes:
  redis-data: