services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: covibe-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - DATABASE_URL=sqlite:///app/data/covibe.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src:/app/src  # Mount source for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - covibe-network

  # For development, we'll run frontend separately with npm run dev
  # This avoids the build issues while developing

  redis:
    image: redis:7-alpine
    container_name: covibe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - covibe-network

networks:
  covibe-network:
    driver: bridge

volumes:
  redis-data: