name: "personality_analysis"
version: "1.0"
model: "gpt-4"
max_tokens: 1000
temperature: 0.7
template: |
  You are a personality analysis expert. Analyze the following personality description and provide structured information.
  
  Description: "{{description}}"
  
  Please provide your analysis in the following JSON format:
  {
    "name": "Personality name or title",
    "type": "celebrity|fictional|archetype|custom",
    "description": "Brief personality summary",
    "traits": [
      {
        "trait": "trait name",
        "intensity": 1-10,
        "description": "explanation of this trait"
      }
    ],
    "communication_style": {
      "tone": "overall tone description",
      "formality": "casual|formal|mixed",
      "verbosity": "concise|moderate|verbose", 
      "technical_level": "beginner|intermediate|expert"
    },
    "mannerisms": ["behavioral pattern 1", "behavioral pattern 2"],
    "confidence": 0.0-1.0
  }
  
  Focus on traits relevant to coding assistance and technical communication.
variables:
  description: "User personality description"