name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from git commits
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Docker Images
          - Backend: `${{ secrets.DOCKER_USERNAME }}/covibe-backend:${{ github.ref_name }}`
          - Frontend: `${{ secrets.DOCKER_USERNAME }}/covibe-frontend:${{ github.ref_name }}`
        draft: false
        prerelease: false
    
    - name: Build and push release images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/covibe-backend:${{ github.ref_name }} -f Dockerfile.backend .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/covibe-frontend:${{ github.ref_name }} ./web
        
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
        docker push ${{ secrets.DOCKER_USERNAME }}/covibe-backend:${{ github.ref_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/covibe-frontend:${{ github.ref_name }}